name: Deploy Pokedex project to github pages.

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - run: npm install
      - run: node ./node_modules/@angular/cli/bin/ng build --configuration=production --base-href=/pokedex/
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/browser

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./

      - run: ls
      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages-upload
          path: ./

      - run: ls
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-upload
